
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: domain_pricing
      MYSQL_USER: domain_user
      MYSQL_PASSWORD: domain_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - domain-network
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    networks:
      - domain-network
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysql_data:

networks:
  domain-network:
    driver: bridge